geekshop/adminapp/urls.py
# from django.conf.urls import url

import adminapp.views as adminapp
from django.urls import re_path

app_name="adminapp"

urlpatterns = [
    re_path(r'^users/create/$', adminapp.user_create, name='user_create'),
    re_path(r'^users/read/$', adminapp.UsersListView.as_view(), name='users'),
    re_path(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),

    re_path(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    re_path(r'^categories/read/$', adminapp.categories, name='categories'),
    re_path(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^products/create/category/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    re_path(r'^products/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import re_path

app_name = "authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),

    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
# from django.conf.urls import url

import basketapp.views as basketapp
from django.urls import re_path

app_name="basketapp"

urlpatterns = [
    re_path(r'^$', basketapp.basket, name='view'),
    re_path(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),

    re_path(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

    

geekshop/geekshop/urls.py
from django.conf.urls import include
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
# from django.conf.urls import url

import mainapp.views as mainapp
from django.urls import re_path

from django.views.decorators.cache import cache_page

app_name="mainapp"

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),

]

    

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name="ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),

    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),

    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='категория активна', db_index=True, default=True)
    
    def __str__(self):
        return self.name

    
class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=512, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='категория активна', db_index=True, default=True)
    
    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import datetime, random, os, json
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings
from django.core.cache import cache

from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
from django.views.decorators.cache import never_cache

JSON_PATH = 'mainapp/json'


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
                order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
            order_by('price')


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
        return json.load(infile)


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    title = 'главная'

    # products = Product.objects.filter(is_active=True, category__is_active=True)[:3]
    products = get_products()[:3]

    content = {
        'title': title,
        'products': products,
    }

    return render(request, 'mainapp/index.html', content)

@never_cache
def products(request, pk=None, page=1):
    title = 'продукты'

    links_menu = get_links_menu()

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)



def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_orederd_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_orederd_by_price(pk)

            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }

            result = render_to_string('mainapp/includes/inc_products_list_content.html', context=content,
                                      request=request)

            return JsonResponse({'result': result})

@never_cache
def product(request, pk):
    title = 'продукты'
    links_menu = get_links_menu()
    product = get_product(pk)

    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'о нас'

    if settings.LOW_CACHE:
        key = f'locations'
        locations = cache.get(key)
        if locations is None:
            locations = load_from_json('contact__locations')
            cache.set(key, locations)
    else:
        locations = load_from_json('contact__locations')

    content = {
        'title': title,
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == '0' %}active{% endif %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}" class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}" class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin:users' %}">админка</a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
        {% if basket %} 
            {{ basket.0.get_total_cost|floatformat:0 }} руб ({{ basket.0.get_total_quantity }} шт)
        {% endif %}
    </span>
</a>

geekshop/mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load static %}

<div class="links clearfix">
    {% include 'mainapp/includes/inc_categories_menu.html' %}
</div>

<div class="products_list">
    <div class="title clearfix">
        <h2>Категория: "{{ category.name|title }}"</h2>
        <div class="paginator">
            {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}"><</a>
            {% endif %}
            <span class="current">
            страница {{ products.number }} из {{ products.paginator.num_pages }}
            </span>
            {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}">></a>
            {% endif %}
        </div>
    </div>
    <div class="category-products clearfix">
        {% for product in products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }} </p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>