geekshop/adminapp/urls.py
# from django.conf.urls import url

import adminapp.views as adminapp
from django.urls import re_path

app_name="adminapp"

urlpatterns = [
    re_path(r'^users/create/$', adminapp.user_create, name='user_create'),
    re_path(r'^users/read/$', adminapp.UsersListView.as_view(), name='users'),
    re_path(r'^users/update/(?P<pk>\d+)/$', adminapp.user_update, name='user_update'),
    re_path(r'^users/delete/(?P<pk>\d+)/$', adminapp.user_delete, name='user_delete'),

    re_path(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    re_path(r'^categories/read/$', adminapp.categories, name='categories'),
    re_path(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    re_path(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^products/create/category/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    re_path(r'^products/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),
    re_path(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import re_path

app_name = "authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),

    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf.urls import include
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory

from mainapp.models import Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'
        
        
class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            
            
class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic.detail import DetailView


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UsersListView,  self).dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)   
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()
    
    content = {'title': title, 'update_form': user_form}
    
    return render(request, 'adminapp/user_update.html', content)
    

@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)
    
    content = {'title': title, 'update_form': edit_form}
    
    return render(request, 'adminapp/user_update.html', content)

	
@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'
    
    user = get_object_or_404(ShopUser, pk=pk)
    
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {
        'title': title,
        'user_to_delete': user
    }
    
    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'
    
    categories_list = ProductCategory.objects.all()
    
    content = {
        'title': title,
        'objects': categories_list
    }
    
    return render(request, 'adminapp/categories.html', content)
    

class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = ('__all__')
    

class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = ('__all__')
    
    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

	
class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())
    

@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'
    
    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')
        
    content = {
        'title': title,
        'category': category,
        'objects': products_list,
    }
    
    return render(request, 'adminapp/products.html', content)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


def product_create(request, pk):
    title = 'продукт/создание'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        #задаем начальное значение категории в форме
        product_form = ProductEditForm(initial={'category': category})
    
    content = {'title': title, 'update_form': product_form, 'category': category}
    
    return render(request, 'adminapp/product_update.html', content)
      

def product_update(request, pk):
    title = 'продукт/редактирование'
       
    edit_product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)
    
    content = {'title': title, 'update_form': edit_form, 'category': edit_product.category}
    
    return render(request, 'adminapp/product_update.html', content)
    
    
def product_delete(request, pk):
    title = 'продукт/удаление'

    product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))

    content = {
        'title': title,
        'product_to_delete': product
    }
    
    return render(request, 'adminapp/product_delete.html', content)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="admin_container">        
        <div class="h2 text-center head">
            Админка
        </div>
        {% block menu %}
            <div class="admin_menu">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        {% endblock %}
        
        
        {% block content %}

        {% endblock %}
        
	</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="categories_list">
		<button class="new_category">
			<a href={% url 'admin:category_create' %}>новая категория</a>
		</button>
		
		{% for object in objects %}
			<div class="category_record {% if not object.is_active %}not_active{% endif %}">
				<div class="category_name">
					{{ object.name|title }}
				</div>
				<div class="category_actions">
					<button>
						<a href={% url 'admin:products' object.pk %}>товары категории</a>
					</button>
					<button>
						<a href={% url 'admin:category_update' object.pk %}>редактировать</a>
					</button>
					<button>
						<a href={% url 'admin:category_delete' object.pk %}>удалить</a>
					</button>
				</div>
				<div class="category_desc">
					{{ object.description|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">отмена</a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:categories' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:categories'%}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите удалить продукт <strong>{{ product_to_delete.name }}</strong>?
        <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' product_to_delete.category.pk %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong> 
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>удалить</a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.category.pk %}>назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>подробная информация</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку продуктов
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="products_list">
		<button class="new_product">
			<a href={% url 'admin:product_create' category.pk %}>новый продукт</a>
		</button>
		
		{% for object in objects %}
			<div class="product_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
				<div class="product_name">
					{{ object.name|title }}
				</div>
				<div class="product_actions">
					<button>
						<a href={% url 'admin:product_read' object.pk %}>подробнее</a>
					</button>
					<button>
						<a href={% url 'admin:product_update' object.pk %}>редактировать</a>
					</button>
					<button>
						<a href={% url 'admin:product_delete' object.pk %}>удалить</a>
					</button>
				</div>
				<div class="summary">
					<b>цена</b>
					<p>{{ object.price }} руб</p>
					<b>количество</b>
					<p>{{ object.quantity }}</p>
				</div>
				<div class="product_desc">
					{{ object.short_desc|title }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ user_to_delete.username }} {% if user_to_delete.first_name %}
                    ({{ user_to_delete.first_name|title }}</b>
                    {% if user_to_delete.last_name %}
                        {{ user_to_delete.last_name|title }}
                    {% endif %})
                {% endif %}?
        <form action="{% url 'admin:user_delete' user_to_delete.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:users' %}">отмена</a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:users' %}">
            к списку пользователей
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="users_list">
		<button class="new_user">
			<a href={% url 'admin:user_create' %}>новый пользователь</a>
		</button>
		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.avatar|media_folder_users }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
					<button>
						<a href={% url 'admin:user_update' object.pk %}>редактировать</a>
					</button>
					<button>
						<a href={% url 'admin:user_delete' object.pk %}>удалить</a>
					</button>
				</div>
				<div class="user_name">
					<p>
						<strong>{{ object.username }}</strong>
					</p>
					<p>
					{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% if object.last_name %}
							<p>{{ object.last_name|title }}</p>
						{% endif %}
					{% endif %}
					</p>
				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}