geekshop/authapp/urls.py
import authapp.views as authapp
from django.urls import re_path

app_name = "authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),

    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
# from django.conf.urls import url

import basketapp.views as basketapp
from django.urls import re_path

app_name="basketapp"

urlpatterns = [
    re_path(r'^$', basketapp.basket, name='view'),
    re_path(r'^add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    re_path(r'^remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),

    re_path(r'^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$', basketapp.basket_edit, name='edit'),
]

    

geekshop/geekshop/urls.py
from django.conf.urls import include
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),

    re_path(r'^order/', include('ordersapp.urls', namespace='order')),

    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
# from django.conf.urls import url

import mainapp.views as mainapp
from django.urls import re_path

from django.views.decorators.cache import cache_page

app_name="mainapp"

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),

]

    

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='категория активна', db_index=True, default=True)
    
    def __str__(self):
        return self.name

    
class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=512, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='категория активна', db_index=True, default=True)
    
    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import datetime, random, os, json
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings
from django.core.cache import cache

from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
from django.views.decorators.cache import never_cache

JSON_PATH = 'mainapp/json'


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
                order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True). \
            order_by('price')


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
        return json.load(infile)


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category, is_active=True).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    title = 'главная'

    # products = Product.objects.filter(is_active=True, category__is_active=True)[:3]
    products = get_products()[:3]

    content = {
        'title': title,
        'products': products,
    }

    return render(request, 'mainapp/index.html', content)

@never_cache
def products(request, pk=None, page=1):
    title = 'продукты'

    links_menu = get_links_menu()

    if pk:
        if pk == '0':
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)



def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_orederd_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_orederd_by_price(pk)

            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }

            result = render_to_string('mainapp/includes/inc_products_list_content.html', context=content,
                                      request=request)

            return JsonResponse({'result': result})

@never_cache
def product(request, pk):
    title = 'продукты'
    links_menu = get_links_menu()
    product = get_product(pk)

    content = {
        'title': title,
        'links_menu': links_menu,
        'product': product,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'о нас'

    if settings.LOW_CACHE:
        key = f'locations'
        locations = cache.get(key)
        if locations is None:
            locations = load_from_json('contact__locations')
            cache.set(key, locations)
    else:
        locations = load_from_json('contact__locations')

    content = {
        'title': title,
        'locations': locations,
    }

    return render(request, 'mainapp/contact.html', content)

geekshop/mainapp/templates/contact.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
    Контакты - {{ block.super }}
{% endblock %}

{% block header %}

    <div class="hero">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
        <h1>наши контакты</h1>
    </div>

{% endblock %}

{% block content %}

    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>
    <div class="clr"></div>

{% endblock %}

{% block footer %}
    {{ block.super }}
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
{% endblock %}

geekshop/mainapp/templates/index.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Главная - {{ block.super }}
{% endblock %}

{% block header %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.pk %}">
                        <img src="{{ product.image }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <h3>{{ product.category.name }}</h3>
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.description }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}

{% block footer %}
    {{ block.super }}
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
{% endblock %}

geekshop/mainapp/templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|capfirst }}
       {% endblock %}
   </title>
   {% block css %}
       <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
   {% endblock %}
   {% block js %}
       <script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
       <script src="{% static 'js/bootstrap.min.js' %}"></script>
       <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
       <script src="{% static 'js/jquery.formset.js' %}"></script>
   {% endblock %}
</head>
<body>
<div class="container">
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}
</div>
<div class="footer">
    {% block footer %}
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    {% endblock %}
</div>
</body>
</html>

geekshop/mainapp/templates/product.html
{% extends 'main.html' %}
{% load static %}
{% block header %}

    <div class="hero-white">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}
{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'includes/inc_products_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>

{% endblock %}
{% block footer %}
    {{ block.super }}
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
{% endblock %}

geekshop/mainapp/templates/products.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
    Продукты - {{ block.super }}
{% endblock %}

{% block header %}

    <div class="hero-white">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="details">
        <div class="links clearfix">
            {% include 'includes/inc_products_menu.html' %}
        </div>
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image }}" alt="horhothot">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image }}" alt=""></a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image }}" alt=""></a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image }}" alt=""></a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price">{{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }}
                </div>
            </div>
        </div>


        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>Стул повышенного качества</h4>
                            <p>Не оторваться. </p>
                        </div>
                    </a>
                </div>

                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <h3>{{ product.category.name }}</h3>
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}
{% block footer %}
    {{ block.super }}
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
{% endblock %}

geekshop/mainapp/templates/products_list.html
{% extends 'main.html' %}
{% load static %}
{% block header %}

    <div class="hero-white">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}
{% block menu %}
    {{ block.super }}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'includes/inc_products_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h3>{{ product.category.name }}</h3>
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

{% block footer %}
    {{ block.super }}
    <p class="small">&copy; GB 2020</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
{% endblock %}